### ISSUE TITLE
Refactor the AdminServlet and JSP into multiple pages using view models

### ISSUE THREAD

**Issue by nowucca** [nowucca/SimpleAffableBean#29]
## background

Right now, the admin pages are all served using the AdminServlet and JSPs underneath the folder src/main/webapp/admin.  Almost all the pages are served conditionally with logic inside /admin/index.jsp.

The AdminServlet JSP files are managed using a separate jsp-config in the main web.xml file.
It is also in there where the login-config specifies how to handle a login success and failure (using /admin/login.jsp and /admin/error.jsp).

## task description: phase 1: split servlet and jsps apart

This task would be to take the AdminServlet and index.jsp and split them into the following servlets and JSPs:  (yes I am changing the url names from viewCustomers to customer etc for simplicity)

AdminHomeServlet, /admin/home.jsp, url-pattern=/admin 
 - update index.jsp to forward to home.jsp just like the main site.
 - this home.jsp would simply be the equivalent empty page we currently get when we first log in.
 - this is in preparation for all requests to go through servlets to make view model classes in phase 2

AdminLoginServlet, /admin/login.jsp, url-pattern=/admin/login
 - instead of the web.xml login-config pointing to the /admin/login.jsp directly, point to /admin/login to run this servlet
 - this is in preparation for all requests to go through servlets to make view model classes in phase 2

AdminErrorServlet, /admin/error.jsp, url-pattern=/admin/error
 -  instead of the web.xml login-config pointing to the /admin/error.jsp directly, point to /admin/error to run this servlet
- this is in preparation for all requests to go through servlets to make view model classes in phase 2

AdminCustomersServlet, /admin/customers.jsp, url-pattern=/admin/customers
 - shows a list of all customers
 - contents of the jsp comes from the relevant part of the existing index.jsp

AdminOrdersServlet, /admin/orders.jsp, url-pattern=/admin/orders
- shows a list of all orders

AdminCustomerServlet, /admin/customer.jsp, url-pattern=/admin/customer
- shows one customer record
 - contents of the jsp come from the relevant part of the existing index.jsp

AdminOrderServlet, /admin/order.jsp, url-pattern=/admin/order
 - shows one order record
 - contents of the jsp comes from the relevant part of the existing index.jsp

Update the jsp-property-group for the admin section (in web.xml)
 - we will have to list /admin/*.jsp or all the new jsps individually instead of the old jsps there.

Checklist for Admin Phase 1
- [ ] Hitting the /admin endpoint should use the AdminLoginServlet at /admin/login to forward to /admin/login.jsp
- [ ] After a failed login we should use the AdminErrorServlet at /admin/error to forward to /admin/error.jsp
- [ ] After successful login the index.jsp should forward to /home.jsp
- [ ] Viewing multiple customers (/admin/customers) should use a servlet and /admin/customers.jsp
- [ ] Viewing multiple orders (/admin/orders) should use a servlet and /admin/orders.jsp
- [ ] Viewing individual customers and orders should also use servlets and the corresponding JSPs
- [ ] The admin header and footer should be present on all pages

## task description phase 2:  View model classes 

If you look at a servlet such as the CheckoutServlet, you can see that for the "GET" page view, we build a view model object using the request and the session, and then simply use a jsp:useBean id="p" and use ${p.property} expressions throughout the JSP.  This is very much easier to understand to start off with, and is the pattern that we want to use for the new Admin pages.

having split the admin pages into their own separate servlets and jsps, we can now effectively approach making the pages conform to the pattern of each having a view model.

This would involve
- [ ] making src/main/java/viewmodel/admin folder, and 
- [ ] making a  new BaseAdminViewModel class.  
- [ ] Then, we would create a ViewModel for each admin page and change the JSPs to use the view model bean and ${p} expressions.  
- [ ] Fortunately we can use the existing admin header and footer JSP fragments as they are.

**Comment by tippyweb** [comment]
Hello Dr. A, since I lost access to Piazza at this time, I'm giving you an update here.  Sorry for the delay, but I started working on this refactor phase 1 just earlier this evening.  Around a half way, I guess...  Will try to complete the phase 1 by Tuesday evening.  I will keep you posted.  Thank you!  deborah

**Comment by nowucca** [comment]
@tippyweb take your time, no rush.

Feel free to call me steve now since we are working together on this.

Please ask questions here I am looking everyday.

If you feel like this is too big a chunk of work, #27 is much less demanding.  But by all means this issue and your questions will help the current class if you tackle it to any level/phase.

**Comment by tippyweb** [comment]
Good morning, Steve, thank you!
At this time, I'm aiming at refactor phase 1 only.  I'd like to come back for phase 2 a little later.

Besides cleaning up some page layout issues, I still need to do the followings for phase 1:
1)  I'm having a problem with displaying the credit card number inside the customer details table on customer.jsp.
2)  AdminLoginServlet
3)  AdminErrorServlet
Hope to be able to finish them tonight.

Two questions:
1)  Somehow I had issues with request.getQueryString().  So, I'm using 
_//        String orderId = request.getQueryString();
        String orderId = request.getParameter("orderId");_
Is this OK?
For getQueryString(), we don't need "orderId=", correct?
Maybe I didn't use the correct parameter...
Please let me know if getQueryString() is better.

2)  For Logout action, should I create AdminLogoutServlet as well?

For #27, yes, that's super interesting!!
I'd like to start working on it from around mid June if that's OK.

Thank you so much, Steve!!

**Comment by tippyweb** [comment]
Good evening, Steve, phase 1 is almost done -- only remaining tasks are AdminLoginServlet and AdminErrorServlet.  So, I understand that we're going to use security annotations instead of web.xml for login/error.  However, /admin is currently forwarded to home.  So, the idea is that inside home.jsp we'll set up security annotations, am I correct?  Then home ==> login ==> (home OR error), is my thinking correct?

BTW, I already added AdminLogoutServlet.
I still would like to have your feedback on getQueryString() method.

Thank you so much, Steve!!

**Comment by nowucca** [comment]
@tippyweb,

If you are ready you can git push origin master and open a pull request so I can see what you're thinking but only when you're ready.

The query string is the whole string after the ? In a URL.  So in the original the URL was /admin/order?1234 (where 1234 is an orderid).  I think, it's late and I'm on my phone.

The old code was assuming it could just get that query string and it would be 1234 without the need to say "/admin/order?orderId=1234" which is wordy.

I'd like to keep it as simple as possible because it's a teaching project ultimately.  If we could be consistent for /admin/order?id and /admin/customer?id that would be great. Bonus points for /admin/order/1234 using request.getPathInfo.  

Now for the other questions.

Let's NOT stop using web.xml for the security.  Annotations is a separate task and it muddied waters here.  No worries though, sometimes biting off less helps.

My idea was in web.xml for login and error to forward to the SERVLETs, rather than the JSPs, using /admin/login and /admin/error.  

Now imagine the customer asking for the home page.
That should go to AdminHomeServlet which will have the security and role requirement as annotations like the existing servlet does.

So the container will take the customer to /admin/login which will hit the AdminLoginServlet and render using /admin/login.jsp.

Then a failed login goes to the error servlet and JSP per checklist.

And I'm ok with successful login redirecting (remember post-redirect-get pattern) to /admin directly.
 or it could be using a redirect to index.jsp, that should use the same tag the regular app does to get to /admin, therefore the AdminHomeServlet and ultimately /admin/home.jsp

I'm suggesting if it's not clear to go ahead and submit the pull request and questions as comments here - it might be faster if I review this stuff once you are ready of course.  

Cheers
Steve

**Comment by tippyweb** [comment]
@nowucca,

Thank you so much for your comments!
I thought your Bonus Points idea excellent and so tried to implement it this evening in vain...
So, I kept the wordy method for the time being.

My apologies not being able to complete the rest of Phase 1 this week...
If it's OK, I'd like to come back to this in mid June, along with #27.

Now, at this time, I'm struggling with submitting my updates to you again :(
Here are the lines from Git Shell:

~\Documents\GitHub\SimpleAffableBean [master ≡ +15 ~6 -0 !]> git push origin master
Everything up-to-date
~\Documents\GitHub\SimpleAffableBean [master ≡ +15 ~6 -0 !]> git commit
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
        modified:   src/main/java/business/customer/Customer.java
        modified:   src/main/java/controller/AdminServlet.java
        modified:   src/main/webapp/WEB-INF/web.xml
        modified:   src/main/webapp/admin/index.jsp
        modified:   src/main/webapp/admin/jspf/header.jspf
        modified:   src/main/webapp/css/affablebean.css

Untracked files:
        .ideaDataSources/
        dataSources/
        src/main/java/controller/AdminCustomerServlet.java
        src/main/java/controller/AdminCustomersServlet.java
        src/main/java/controller/AdminErrorServlet.java
        src/main/java/controller/AdminHomeServlet.java
        src/main/java/controller/AdminLoginServlet.java
        src/main/java/controller/AdminLogoutServlet.java
        src/main/java/controller/AdminOrderServlet.java
        src/main/java/controller/AdminOrdersServlet.java
        src/main/webapp/admin/customer.jsp
        src/main/webapp/admin/customers.jsp
        src/main/webapp/admin/home.jsp
        src/main/webapp/admin/order.jsp
        src/main/webapp/admin/orders.jsp

no changes added to commit
~\Documents\GitHub\SimpleAffableBean [master ≡ +15 ~6 -0 !]>

Any idea what's missing/needed to be done?
Pull request is not enabled from Github Desktop.
Any advice is appreciated.

Thank you so much!!

**Comment by tippyweb** [comment]
BTW, git commit THEN git push origin master created the same output.

**Comment by tippyweb** [comment]
@nowucca,

Please ignore my error report earlier.
I guess it went well just a few seconds ago.
Please verify this.

I also updated AdminLoginServlet and AdminErrorServlet items.
However, at this time, AdminErrorServlet is not working.
But everything else should be OK.
If you could take a look at the following, that would be great:
1)  AdminErrorServlet error handling
2)  request.getPathInfo() implementation -- I tested my code in the /admin/home.jsp for the customer form only.  Currently commented out.

I'm not too happy with the Admin Menu items.
When I come back, I'd like to move the Admin Menus to the header to reduce clutters.
Any comments/feedback will be appreciated!!

Thank you again!!

**Comment by nowucca** [comment]
Hi @tippyweb

It's all pushed to YOUR repository and I can browse it.

I'm going to see if I can browse to YOUR master branch and make comments on the files.  You could look over them and fix those, and re-push them to github using git push origin master.

What I can propose is the following:
- it's always fine to come back to this later
- I can review the code on your repository and make suggestions
- No rush to merge it into the master branch yet, although we could choose to.

The one problem we are going to run into is that you need to keep your repository up to date with changes I am making in the meantime.....

# Keeping up to date

If we just decide to merge or take by hand what you have in your repository, you won't need to do this stuff now.  But, if you want to really learn git and collaboration over time, this becomes relevant.  If this all seems like too much work, I am happy for you to do Step 5 below with what you have and I'll patch things up, otherwise I'm happy to wait as well!

Over time it becomes second nature.

One thing that's going to be an issue is the fact that the master repository has moved on a bit and you'll need to keep your master repository up to date.  For example I also realized I needed getCcNumber and added it back into Customer.java.  That's going to turn into a conflict once you get up to date.  But that's ok, I have some steps to guide you through.

So there are 3 repositories in the picture.  
1) my master repository on github.  (nowucca/SimpleAffableBean)  
2) your local repository on Windows (tippyweb/SimpleAffableBean on your windows box)
3) your repository on github (tippyweb/SimpleAffableBean that I can review on github).

The steps to get up to date, meaning you want to bring changes from 1) into 2) and merge them.
(ideally only THEN would we push the update and changes for #29 from 2) into 3) and THEN create a pull request).

Step 1: (once only)
   - Make sure you associate an upstream reference from 2) to 1) [using this guide](https://help.github.com/articles/configuring-a-remote-for-a-fork/)

Step 2: (every time you want to get the latest updates)
   - Pull latest changes from 1) into 2)  [see "syncing a fork guide here](https://help.github.com/articles/syncing-a-fork/)

Step 3: (every time you face conflicts)
   - As indicate above this will likely generate conflicts.  [This article by far is the best for conflict resolution explanation](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/) 

Step 4:  Push the changes to your Github repository
   - Once you have merged and resolved the changes from 1), do another git push origin master to move all the merges and latest fixes to 3).

Step 5: Create a pull request to merge changes back into my repository.
   - Then you just have to create the pull request to request for me to merge it back into my repository.  To make the pull request, log onto the github website and choose "New Pull Request" green button after browsing to this page: https://github.com/nowucca/SimpleAffableBean/pulls

**Comment by nowucca** [comment]
Okay I went through and made comments on your latest commit: https://github.com/tippyweb/SimpleAffableBean/commit/bdb22f131a27a0dd7176a77672077e6525759eda

If you don't see them in email nicely then hopefully that link will help.

The error servlet should not have the role constraint on it is the issue I think you have been fighting.  Chicken and egg problem, hard to spot!

I'm really happy to see that you have the right instincts for all of this.  Please take my comments in a friendly spirit.  It's very encouraging to see such good progress.

I understand if you are out of time - if you do want me to merge all this stuff by hand as is and fix it up, it is really very close to being done.  I'm also happy to wait - I'll leave it up to you.

**Comment by tippyweb** [comment]
@nowucca, thank you so much for all your reviews and comments!!
I greatly appreciate your "Keeping up to date" write-up -- I will definitely start practicing this by the time I come back in mid June.  Yes, I realize that my code is about 2-3 weeks old compared to your master repository...  I appreciate your patience while I'm getting used to Git practices...  I thank you very much for your line, "Over time it becomes second nature" -- I will keep this image in my mind when I learn your steps above!! :)

Please let me come back to your comments later today.  With your timely assistance, I also do feel phase 1 completion is close!  I will keep you posted this evening!  Have a wonderful day!!

**Comment by nowucca** [comment]
Hi it's been a long day!

Let's leave the urls as parameters the way it works now and fix all the links if we can.

I think it would be easier to go ahead and create the pull request if you get a chance, and just note the issues you face.

I'll be traveling from Monday but I'll check in next week and merge, fix and push your changes in whatever state you can get them too.

**Comment by nowucca** [comment]
Hmm, I'm on my phone so it is really hard to do all the comment review.  That's why I said it's ok to leave it the way it is.

I'm also happy to wait.  There's no rush.  

So from memory the pathInfo call gives you a string and you can use string.split("/") to get a string array and the 3rd element is the customerid - a little circuitous but nothing a helper method cannot handle.

I cannot easily tell what's going on with the error servlet by just looking at the code, so we may have to debug that later.

I'll try scrolling through and responding for a bit on the comments, but we don't have to let the perfect be the enemy of the good, we can merge it whenever you create the pull request.

It seems like we are both a little busier coming up but I look forward to hearing from you when you can get back to it.  Happy summer!

**Comment by tippyweb** [comment]
@nowucca 

I just pushed additional updates and created a new pull request.  Hope you can see it.
I retried to fix the getParameter() and the j_security_check error page issues, but failed again!
I'd like to work on them when I come back in mid June.
I deleted the getCcNumber() from Customer.java and so there shouldn't be any conflict.

Please let me know if I missed something.

Thank you so much again, Steve, and you have a productive trip next week!!

deborah

**Comment by tippyweb** [comment]
Relevant Stackoverflow posts:
https://stackoverflow.com/questions/10838296/j-security-check-on-tomcat
https://stackoverflow.com/questions/34128361/appending-form-input-value-to-action-url-as-path

**Comment by nowucca** [comment]
Hi @tippyweb,
I'm wondering now that you have an example view model page if you wanted to tackle phase 2 of this bug?

## task description phase 2: View model classes

If you look at a servlet such as the CheckoutServlet, you can see that for the "GET" page view, we build a view model object using the request and the session, and then simply use a jsp:useBean id="p" and use ${p.property} expressions throughout the JSP. This is very much easier to understand to start off with, and is the pattern that we want to use for the new Admin pages.

having split the admin pages into their own separate servlets and jsps, we can now effectively approach making the pages conform to the pattern of each having a view model.

This would involve

* (DONE) making src/main/java/viewmodel/admin folder, and
*  making a new BaseAdminViewModel class. (Grow it as you see common features using the BaseViewModel as a guide) 

* Then, we would create a ViewModel for each admin page and change the JSPs to use the view model bean and ${p} expressions.  One example is in AdminSessionViewModel already and the /admin/session.jsp 

* Fortunately we can use the existing admin header and footer JSP fragments as they are.  This means because they are static we can simply leave them alone and do not have to model them as view models - just leave the code for them in JSPs as is.

What do you think?

**Comment by tippyweb** [comment]
Hello @nowucca 

Of course, I would love to do that!!  Thank you so much for your writeups!!  Will get back to you next week if that's OK since I need to take care of something else this week...  It'll be around Wednesday next week to get it started.  Thank you so much again, @nowucca , for your assistance for #27!!!

**Comment by tippyweb** [comment]
Hello @nowucca 

Sorry, I'm getting behind...  I already downloaded your master last night.  Just started looking into this issue this evening.  My availability is limited through Tuesday, but would like to finish it by Wednesday or Thursday next week.  I will keep you posted.  Have a great weekend!!

**Comment by tippyweb** [comment]
Hello @nowucca 

My apologies for this delay...
I just made a new pull request for the Admin View Model updates.
Please note that I didn't include the following pages because they are static:
error.jsp
home.jsp
index.jsp
login.jsp
For the BaseAdminViewModel, I'm not really sure if it was done correctly...
Your reviews are appreciated.
Thank you so much, @nowucca !!!

**Comment by nowucca** [comment]
Hi @tippyweb, so good to see you!

I only just saw that you're back AND you've pushed something today - summer class is busy! And learning about ViewModels this time, so this is timely!

I'm going to look at this over the weekend.
I'll try to just make comments to give you a chance to fix anything first, if it's needed this time.

Take care!

**Comment by nowucca** [comment]
Thanks again @tippyweb, closed out thanks to pull requests #35, #36
